language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
    - pip install -r requirements.txt
    # needs to be able to be installed without error on all versions
    - pip install .

stages:
  - codestyle
  - test
jobs:
  include:
    - stage: codestyle
      python: "3.7"
      install:
        - pip install pycodestyle
      script:
        - bin/pep8

      # will run on all defined python versions above
    - stage: test
      script:
        - bin/run_tests
